name: Build All Versions

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        minecraft_version: ['1.21.8', '1.21.7', '1.21.6', '1.21.5', '1.21.4']
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      
      - name: Copy version-specific properties
        run: cp gradle-${{ matrix.minecraft_version }}.properties gradle.properties
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Build with Gradle
        run: ./gradlew build
      
      - name: Rename artifact
        run: |
          cd build/libs
          for file in *.jar; do
            if [[ ! "$file" =~ "-sources.jar" ]] && [[ ! "$file" =~ "-dev.jar" ]]; then
              mv "$file" "${file%.jar}-mc${{ matrix.minecraft_version }}.jar"
            fi
          done
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zen-additions-mc${{ matrix.minecraft_version }}
          path: build/libs/*-mc${{ matrix.minecraft_version }}.jar
          if-no-files-found: error
  
  combine-artifacts:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Combine artifacts
        run: |
          mkdir -p combined
          find artifacts -name "*.jar" -exec cp {} combined/ \;
      
      - name: Upload combined artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zen-additions-all-versions
          path: combined/*.jar
          if-no-files-found: error
