name: Build and Release

on:
    workflow_dispatch:
        inputs:
            release_tag:
                description: 'Tag to build/release'
                required: true

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                version: ['1.21.4-1.21.5', '1.21.6-1.21.7', '1.21.8-1.21.9']

        steps:
            - name: Checkout repository at tag
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.inputs.release_tag }}   # ✅ Checkout the actual tag

            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v4

            - name: Grant execute permission for gradlew
              run: chmod +x gradlew

            - name: Build ${{ matrix.version }}
              run: ./gradlew build -PbuildTarget=${{ matrix.version }}

            - name: Upload artifact for ${{ matrix.version }}
              uses: actions/upload-artifact@v4
              with:
                  name: zen-additions-${{ matrix.version }}
                  path: build/libs/*.jar
                  if-no-files-found: error

    release:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout repository at tag
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.inputs.release_tag }}  # ✅ Checkout same tag for release

            - name: Download all artifacts
              uses: actions/download-artifact@v4
              with:
                  path: artifacts

            - name: Create GitHub Release
              uses: marvinpinto/action-automatic-releases@latest
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  automatic_release_tag: ${{ github.event.inputs.release_tag }}
                  prerelease: false
                  title: "Release ${{ github.event.inputs.release_tag }}"
                  files: artifacts/**/*
